### ISSUE TITLE
Execution issue

### ISSUE THREAD

**Issue by Karimalameh19** [omrawal/Signature-Matching#2]
The code is not outputting the similarity score for the signatures and seems to be stuck at the matching step  
![Screenshot 2024-05-13 151609](https://github.com/omrawal/Signature-Matching/assets/104790552/eda30929-d0c1-46bd-aab1-c8eb0151fb99)

**Comment by omrawal** [comment]
HI Thanks for writing
so i forgot to mention this that results will only be displayed when you close both the displayed windows.
this was added so that user knows which 2 images are being compared
